### ISSUE TITLE
Please also keep track of the circle's Total Energy Usage [FEATURE]

### ISSUE THREAD

**Issue by slowfellow** [plugwise/plugwise-beta#185]
**Is your feature request related to a problem? Please describe.**
I would like to have insight into the energy consumption of the device over more than 1 or 2 days.. so please create this parameter.

**Describe the solution you'd like**
Since there are total power(energy) consumption (kWh) available for today and yesterday it should be possible to create a Total Consumed Energy counter out of this. There should be a counter that hold the total consumed energy until today. (This parameter only has to be updated once a day). Then Total consumed energy is equal to this counter + total consumption for today.

**Describe alternatives you've considered**
Can't thing of a different better solution

**Home Assistant (please complete the following information):**
 - Version: 0.16.1
 - Deployment: 'raspberry/hassio' 
 - Installed plugwise version:  'plugwise-beta'
 - Installed through 'HACS'

**Additional context**

**Comment by CoMPaTech** [comment]
Though it might not be fully sufficient, have you looked at https://www.home-assistant.io/integrations/utility_meter/? I don't recall the other options (within HA) but bouwew or brefra might know them top of mind, I'll check tomorrow.

**Comment by bouwew** [comment]
@slowfellow In principle, plugwise-beta, the Stick-related part, should be able to show all information that is shown in Plugwise Source. I write "in principle" because there is a problem: we don't know everything about the communication between the Stick and the connected devices. We only know a part, from other people that have performed some reverse-engineer on the protocol that Plugwise has used. At the moment we don't know how to get the total numbers out of the Circles, etc.

As the next best thing, please have a look at the Utility-Meter component as suggested by @CoMPaTech, or you could create your own total energy meter, please search on the HA Community forum for similar requests, with solutions.

**Comment by brefra** [comment]
@slowfellow, What should be the stating point in time of the requested total energy measurement?

From all the research I've done so far I have not seen any possibility of the existence of a total powercounter or something similar.
The devices do store the consumed (or produced) power of each hour in local memory. So the current "today" and "yesterday" sensors values are the sum of the 24 (hour) values retrieved from the device memory.

As the memory of the device is limited and overwritten after a while (and depending on a regular clock sync) there is no way to get a reliable total energy use from the plugwise devices.
Unless you want to have a sensor with the total energy of a limited timespan (like a week or month) which is available in the memory of the plugwise device?

The only proper way to track the total energy usage over a longer timespan is to do it outside of this (custom) integration. i.e the suggested utility-meter. Which will be a measurement of consumed/produced energy starting from the specified point in time.

**Comment by bouwew** [comment]
@slowfellow
Please test plugwise-beta v0.17.0a7.

**Comment by bouwew** [comment]
Closed.
